import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useDispatch } from "react-redux"; //to provide changes
import { useSelector } from "react-redux"; //to display change in state dispatched b the dispatcher
import { useState } from "react";
import { login, logout } from "../features/user";
import { useRouter } from "next/router";
import axios from "axios";

export default function Home() {
  const dispatch = useDispatch();
  const router = useRouter();

  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [pass, setPass] = useState("");

  const handleClick = () => {
    dispatch(
      login({
        firstName,
        lastName,
        email,
        password: pass,
      })
    );

    router.push("/Login");
  };

  const handleSubmit = (event) => {
    event.preventDefault();

    const user = {
      first_name: firstName,

      last_name: lastName,

      email: email,

      password: pass,
    };

    axios.post(`http://13.127.127.40/api/user/`, { user }).then((res) => {
      console.log("this is response", res.data);
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form
        className={styles.container}
        // onSubmit={(e) => {
        //   handleSubmit(e);
        // }}
      >
        <label htmlFor="firstName">First Name</label>
        <input
          type="text"
          placeholder="enter firstname"
          onChange={(e) => {
            setFirstName(e.target.value);
          }}
          required
        />
        <label htmlFor="lastname">Last Name</label>
        <input
          type="text"
          placeholder="enter lastaname"
          onChange={(e) => {
            setLastName(e.target.value);
          }}
          required
        />
        <label htmlFor="email">Email</label>
        <input
          type="email"
          placeholder="enter email"
          onChange={(e) => {
            setEmail(e.target.value);
          }}
          required
        />
        <label htmlFor="password">Password</label>
        <input
          type="password"
          placeholder="enter your password"
          onChange={(e) => {
            setPass(e.target.value);
          }}
        />
        <button
          type="submit"
          onClick={(e) => {
            handleSubmit(e);
            dispatch(
              login({
                firstName,
                lastName,
                email,
                password: pass,
              })
            );
            e.preventDefault();
            router.push("/Login");
          }}
        >
          Submit
        </button>
      </form>
    </div>
  );
}
